# These are supported funding model platforms
fgf

github: [dr-mushtaq]
patreon: yourPatreonUsername
ko_fi: yourKoFiUsername
buy_me_a_coffee: yourBuyMeACoffeeUsername
custom: ['https://paypal.me/maths9075@gmail.com']
